[colors.primary]
background = "#102029"
foreground = "#EDEEF0"

[colors.normal]
black = "#102029"
blue = "#71AAC5"
cyan = "#7CBBC0"
green = "#7CABA3"
magenta = "#F4ADB1"
red = "#C9647E"
white = "#D9DBE3"
yellow = "#C7C8B7"

[colors.bright]
black = "#103F56"
blue = "#A7CBE3"
cyan = "#A5D3D9"
green = "#ADD4CF"
magenta = "#F8CBCE"
red = "#D87E8F"
white = "#EDEEF0"
yellow = "#EBDECD"

[colors.cursor]
cursor = "#EDEEF0"

[colors]
indexed_colors = [
    {color = "#EDEEF0", index =  16},
    {color = "#EDEEF0", index =  17},
    {color = "#EDEEF0", index =  18},
    {color = "#EDEEF0", index =  19},
    {color = "#EDEEF0", index =  20},
    {color = "#EDEEF0", index =  21},
    {color = "#EDEEF0", index =  22},
    {color = "#EDEEF0", index =  23},
    {color = "#EDEEF0", index =  24},
    {color = "#EDEEF0", index =  25},
    {color = "#EDEEF0", index =  26},
    {color = "#EDEEF0", index =  27},
    {color = "#EDEEF0", index =  28},
    {color = "#EDEEF0", index =  29},
    {color = "#EDEEF0", index =  30},
    {color = "#EDEEF0", index =  31},
    {color = "#EDEEF0", index =  32},
    {color = "#EDEEF0", index =  33},
    {color = "#EDEEF0", index =  34},
    {color = "#EDEEF0", index =  35},
    {color = "#EDEEF0", index =  36},
    {color = "#EDEEF0", index =  37},
    {color = "#EDEEF0", index =  38},
    {color = "#EDEEF0", index =  39},
    {color = "#EDEEF0", index =  40},
    {color = "#EDEEF0", index =  41},
    {color = "#EDEEF0", index =  42},
    {color = "#EDEEF0", index =  43},
    {color = "#EDEEF0", index =  44},
    {color = "#EDEEF0", index =  45},
    {color = "#EDEEF0", index =  46},
    {color = "#EDEEF0", index =  47},
    {color = "#EDEEF0", index =  48},
    {color = "#EDEEF0", index =  49},
    {color = "#EDEEF0", index =  50},
    {color = "#EDEEF0", index =  51},
    {color = "#EDEEF0", index =  52},
    {color = "#EDEEF0", index =  53},
    {color = "#EDEEF0", index =  54},
    {color = "#EDEEF0", index =  55},
    {color = "#EDEEF0", index =  56},
    {color = "#EDEEF0", index =  57},
    {color = "#EDEEF0", index =  58},
    {color = "#EDEEF0", index =  59},
    {color = "#EDEEF0", index =  60},
    {color = "#EDEEF0", index =  61},
    {color = "#EDEEF0", index =  62},
    {color = "#EDEEF0", index =  63},
    {color = "#EDEEF0", index =  64},
    {color = "#EDEEF0", index =  65},
    {color = "#EDEEF0", index =  66},
    {color = "#EDEEF0", index =  67},
    {color = "#EDEEF0", index =  68},
    {color = "#EDEEF0", index =  69},
    {color = "#EDEEF0", index =  70},
    {color = "#EDEEF0", index =  71},
    {color = "#EDEEF0", index =  72},
    {color = "#EDEEF0", index =  73},
    {color = "#EDEEF0", index =  74},
    {color = "#EDEEF0", index =  75},
    {color = "#EDEEF0", index =  76},
    {color = "#EDEEF0", index =  77},
    {color = "#EDEEF0", index =  78},
    {color = "#EDEEF0", index =  79},
    {color = "#EDEEF0", index =  80},
    {color = "#EDEEF0", index =  81},
    {color = "#EDEEF0", index =  82},
    {color = "#EDEEF0", index =  83},
    {color = "#EDEEF0", index =  84},
    {color = "#EDEEF0", index =  85},
    {color = "#EDEEF0", index =  86},
    {color = "#EDEEF0", index =  87},
    {color = "#EDEEF0", index =  88},
    {color = "#EDEEF0", index =  89},
    {color = "#EDEEF0", index =  90},
    {color = "#EDEEF0", index =  91},
    {color = "#EDEEF0", index =  92},
    {color = "#EDEEF0", index =  93},
    {color = "#EDEEF0", index =  94},
    {color = "#EDEEF0", index =  95},
    {color = "#EDEEF0", index =  96},
    {color = "#EDEEF0", index =  97},
    {color = "#EDEEF0", index =  98},
    {color = "#EDEEF0", index =  99},
    {color = "#EDEEF0", index = 100},
    {color = "#EDEEF0", index = 101},
    {color = "#EDEEF0", index = 102},
    {color = "#EDEEF0", index = 103},
    {color = "#EDEEF0", index = 104},
    {color = "#EDEEF0", index = 105},
    {color = "#EDEEF0", index = 106},
    {color = "#EDEEF0", index = 107},
    {color = "#EDEEF0", index = 108},
    {color = "#EDEEF0", index = 109},
    {color = "#EDEEF0", index = 110},
    {color = "#EDEEF0", index = 111},
    {color = "#EDEEF0", index = 112},
    {color = "#EDEEF0", index = 113},
    {color = "#EDEEF0", index = 114},
    {color = "#EDEEF0", index = 115},
    {color = "#EDEEF0", index = 116},
    {color = "#EDEEF0", index = 117},
    {color = "#EDEEF0", index = 118},
    {color = "#EDEEF0", index = 119},
    {color = "#EDEEF0", index = 120},
    {color = "#EDEEF0", index = 121},
    {color = "#EDEEF0", index = 122},
    {color = "#EDEEF0", index = 123},
    {color = "#EDEEF0", index = 124},
    {color = "#EDEEF0", index = 125},
    {color = "#EDEEF0", index = 126},
    {color = "#EDEEF0", index = 127},
    {color = "#EDEEF0", index = 128},
    {color = "#EDEEF0", index = 129},
    {color = "#EDEEF0", index = 130},
    {color = "#EDEEF0", index = 131},
    {color = "#EDEEF0", index = 132},
    {color = "#EDEEF0", index = 133},
    {color = "#EDEEF0", index = 134},
    {color = "#EDEEF0", index = 135},
    {color = "#EDEEF0", index = 136},
    {color = "#EDEEF0", index = 137},
    {color = "#EDEEF0", index = 138},
    {color = "#EDEEF0", index = 139},
    {color = "#EDEEF0", index = 140},
    {color = "#EDEEF0", index = 141},
    {color = "#EDEEF0", index = 142},
    {color = "#EDEEF0", index = 143},
    {color = "#EDEEF0", index = 144},
    {color = "#EDEEF0", index = 145},
    {color = "#EDEEF0", index = 146},
    {color = "#EDEEF0", index = 147},
    {color = "#EDEEF0", index = 148},
    {color = "#EDEEF0", index = 149},
    {color = "#EDEEF0", index = 150},
    {color = "#EDEEF0", index = 151},
    {color = "#EDEEF0", index = 152},
    {color = "#EDEEF0", index = 153},
    {color = "#EDEEF0", index = 154},
    {color = "#EDEEF0", index = 155},
    {color = "#EDEEF0", index = 156},
    {color = "#EDEEF0", index = 157},
    {color = "#EDEEF0", index = 158},
    {color = "#EDEEF0", index = 159},
    {color = "#EDEEF0", index = 160},
    {color = "#EDEEF0", index = 161},
    {color = "#EDEEF0", index = 162},
    {color = "#EDEEF0", index = 163},
    {color = "#EDEEF0", index = 164},
    {color = "#EDEEF0", index = 165},
    {color = "#EDEEF0", index = 166},
    {color = "#EDEEF0", index = 167},
    {color = "#EDEEF0", index = 168},
    {color = "#EDEEF0", index = 169},
    {color = "#EDEEF0", index = 170},
    {color = "#EDEEF0", index = 171},
    {color = "#EDEEF0", index = 172},
    {color = "#EDEEF0", index = 173},
    {color = "#EDEEF0", index = 174},
    {color = "#EDEEF0", index = 175},
    {color = "#EDEEF0", index = 176},
    {color = "#EDEEF0", index = 177},
    {color = "#EDEEF0", index = 178},
    {color = "#EDEEF0", index = 179},
    {color = "#EDEEF0", index = 180},
    {color = "#EDEEF0", index = 181},
    {color = "#EDEEF0", index = 182},
    {color = "#EDEEF0", index = 183},
    {color = "#EDEEF0", index = 184},
    {color = "#EDEEF0", index = 185},
    {color = "#EDEEF0", index = 186},
    {color = "#EDEEF0", index = 187},
    {color = "#EDEEF0", index = 188},
    {color = "#EDEEF0", index = 189},
    {color = "#EDEEF0", index = 190},
    {color = "#EDEEF0", index = 191},
    {color = "#EDEEF0", index = 192},
    {color = "#EDEEF0", index = 193},
    {color = "#EDEEF0", index = 194},
    {color = "#EDEEF0", index = 195},
    {color = "#EDEEF0", index = 196},
    {color = "#EDEEF0", index = 197},
    {color = "#EDEEF0", index = 198},
    {color = "#EDEEF0", index = 199},
    {color = "#EDEEF0", index = 200},
    {color = "#EDEEF0", index = 201},
    {color = "#EDEEF0", index = 202},
    {color = "#EDEEF0", index = 203},
    {color = "#EDEEF0", index = 204},
    {color = "#EDEEF0", index = 205},
    {color = "#EDEEF0", index = 206},
    {color = "#EDEEF0", index = 207},
    {color = "#EDEEF0", index = 208},
    {color = "#EDEEF0", index = 209},
    {color = "#EDEEF0", index = 210},
    {color = "#EDEEF0", index = 211},
    {color = "#EDEEF0", index = 212},
    {color = "#EDEEF0", index = 213},
    {color = "#EDEEF0", index = 214},
    {color = "#EDEEF0", index = 215},
    {color = "#EDEEF0", index = 216},
    {color = "#EDEEF0", index = 217},
    {color = "#EDEEF0", index = 218},
    {color = "#EDEEF0", index = 219},
    {color = "#EDEEF0", index = 220},
    {color = "#EDEEF0", index = 221},
    {color = "#EDEEF0", index = 222},
    {color = "#EDEEF0", index = 223},
    {color = "#EDEEF0", index = 224},
    {color = "#EDEEF0", index = 225},
    {color = "#EDEEF0", index = 226},
    {color = "#EDEEF0", index = 227},
    {color = "#EDEEF0", index = 228},
    {color = "#EDEEF0", index = 229},
    {color = "#EDEEF0", index = 230},
    {color = "#EDEEF0", index = 231},
    {color = "#EDEEF0", index = 232},
    {color = "#EDEEF0", index = 233},
    {color = "#EDEEF0", index = 234},
    {color = "#EDEEF0", index = 235},
    {color = "#EDEEF0", index = 236},
    {color = "#EDEEF0", index = 237},
    {color = "#EDEEF0", index = 238},
    {color = "#EDEEF0", index = 239},
    {color = "#EDEEF0", index = 240},
    {color = "#EDEEF0", index = 241},
    {color = "#EDEEF0", index = 242},
    {color = "#EDEEF0", index = 243},
    {color = "#EDEEF0", index = 244},
    {color = "#EDEEF0", index = 245},
    {color = "#EDEEF0", index = 246},
    {color = "#EDEEF0", index = 247},
    {color = "#EDEEF0", index = 248},
    {color = "#EDEEF0", index = 249},
    {color = "#EDEEF0", index = 250},
    {color = "#EDEEF0", index = 251},
    {color = "#EDEEF0", index = 252},
    {color = "#EDEEF0", index = 253},
    {color = "#EDEEF0", index = 254},
    {color = "#EDEEF0", index = 255}
]
